-- Step 1: Update existing TERM values to SEMESTER values
UPDATE "terms" SET "termNumber" = 'SEMESTER_1' WHERE "termNumber" = 'TERM_1';
UPDATE "terms" SET "termNumber" = 'SEMESTER_2' WHERE "termNumber" = 'TERM_2';

-- Step 2: Drop old enum values (Prisma will handle this via db push)
-- The ALTER TYPE statements will be generated by Prisma